mongo:
  host: localhost
  port: 27017
  databaseName: data_set

data.kafka.consumers:
  bootstrapServers:
    - 127.0.0.1:9092
  groupId: "data-saver"
  concurrency: 1
#logging.level.reactor.kafka.receiver: info
#logging.level.org.springframework.data.mongodb: debug
#logging.level.org.mongodb: debug
#logging.level.com.example.datasaver.configuration.mongodb: debug