version: '2'

services:

  zookeeper:
    image: 'wurstmeister/zookeeper:3.4.6'
    ports:
      - '2181:2181'

  zman:
    image: 'guras256/zman:1.0.0.SNAPSHOT'
    ports:
      - '8888:8080'
    environment:
      INITIAL_SERVERS: 'local,zookeeper:2181'

  kafka:
    image: 'wurstmeister/kafka:1.0.0'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: '127.0.0.1'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "messages:4:1"
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    depends_on: 
      - 'zookeeper'

  mongo:
    image: 'mongo:3.4'
    ports:
      - '27017:27017'